server:
  port: 8083
spring:
  application:
    name: company-frame
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://123.56.30.106:3306/company_frame?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      ##################    ?????????    ################
      initial-size: 5  #?????????????????????????
      max-active: 20   #
      min-idle: 5
      max-wait: 5
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall
  #redis??????
  redis:
    # redis ?????????
    host: 123.56.30.106
    # Redis ????????????
    port: 6379
    #redis ???????????????? ?????????
    #password:
    lettuce:
      pool:
        max-active: 1024   #????????????????????????????????
        max-wait: PT10S      # ????????????????????????????????10??
        max-idle: 200 # ??????§Ö?????????
        min-idle: 0   # ??????§Ö?§³????????
      shutdown-timeout: PT10S

mybatis:
  type-aliases-package: com.feng.companyframe.bean
  #???????????? ??????? mapper.xml ??¡¤??
  mapper-locations: classpath:mapper/*.xml
  #???? ? ?
#swagger
swagger2:
  enable: true

